### ISSUE TITLE
Method Not Allowed The method is not allowed for the requested URL.

### ISSUE THREAD

**Issue by fakhrulfa** [heimzza/flask-ml-service#1]
Hi,

Im trying to follow ur solution about create server of flask from machine learning model. But, i got an error like this:
405 Bad Request
Method Not Allowed
The method is not allowed for the requested URL.

Im using SVR to predict close price of stocks, heres my code of the server (flask):
```
# Import libraries
import numpy as np
from flask import Flask, request, jsonify
import pickle
import socket

app = Flask(__name__)

# Load the model
model = pickle.load(open('modelfix.pkl', 'rb'))


@app.route('/')
def helloIndex():
    return 'Hello World from Python Flask!'


@app.route('/api', methods=['POST'])
def predict():
    # Get the data from the POST request.
    data = request.get_json(force=True)

    buka = data["Open"]
    tinggi = data["High"]
    rendah = data["Low"]
    adj = data["Adj Close"]

    # Make prediction using model loaded from disk as per the data.
    prediction = model.predict([[buka, rendah, tinggi, adj]])

    # Take the first value of prediction
    return jsonify(int(prediction[0]))

if __name__ == '__main__':
    app.run(port=5000)
```

I dont know whats wrong with this, hope u can help. Thanks!

**Comment by heimzza** [comment]
Hi, is the server not running? Or it's running but you can't make post
request?

12 Kas 2019 Sal 10:33 tarihinde fakhrulfa <notifications@github.com> şunu
yazdı:

**Comment by heimzza** [comment]
hi, the error has been solved. thanks for posting that
